### ISSUE TITLE
On Ubuntu 20.04, postgresql.conf is left with 640 permission, should be 644

### ISSUE THREAD

**Issue by dsudar** [ome/ansible-role-postgresql#23]
When installing on a raw Ubuntu 20.04 without postgres pre-installed, the file /etc/postgresql/11/main/postgresql.conf is left with 640 permission which causes trouble for omero-server:

omero-server@ip-172-31-48-38:~$ omero admin diagnostics

================================================================================
OMERO Diagnostics (admin) 5.9.2
================================================================================

Commands:   java -version                  1.8.0     (/usr/bin/java)
Commands:   python -V                      3.8.5     (/opt/omero/server/venv3/bin/python)
Commands:   icegridnode --version          3.6.5     (/opt/ice/bin/icegridnode)
Commands:   icegridadmin --version         3.6.5     (/opt/ice/bin/icegridadmin)
Commands:   psql --version                 error:'NoneType' object has no attribute 'group'
Commands:   openssl version                1.1.1     (/usr/bin/openssl)

Fix by changing the permissions to 644.

**Comment by sbesson** [comment]
Hi @dsudar thanks for the report. The permissions for the configuration file are defined into

https://github.com/ome/ansible-role-postgresql/blob/b0fc0994611691988d85eee39f3786e0473a5265/tasks/initialise.yml#L35

and were set to `640` in https://github.com/ome/ansible-role-postgresql/commit/4c86c716c76576f8621efb4e2bfaf0dc5ec4a900. I picked the most conservative choice assuming this file would not need world access but looking around I see similar reports in the Debian. Do you have the output of `psql --version` when the permissions are set to `640` since `omero diagnostics` fails to parse it and swallows the output?

Overall, no objections to setting this to `644` if that ensures maximal compatibility with all operating systems without compromising some sensitive information.

**Comment by dsudar** [comment]
Hi Sebastien,
Once I changed the permissions to 644, omero admin diagnostics gave:
```
omero-server@ip-172-31-48-38:~$ omero admin diagnostics

================================================================================
OMERO Diagnostics (admin) 5.9.2
================================================================================

Commands:   java -version                  1.8.0     (/usr/bin/java)
Commands:   python -V                      3.8.5     (/opt/omero/server/venv3/bin/python)
Commands:   icegridnode --version          3.6.5     (/opt/ice/bin/icegridnode)
Commands:   icegridadmin --version         3.6.5     (/opt/ice/bin/icegridadmin)
Commands:   psql --version                 11.12     (/usr/bin/psql)
Commands:   openssl version                1.1.1     (/usr/bin/openssl)

```
And on another system where I installed postgres 11 using the regular installation instructions on: https://docs.openmicroscopy.org/omero/5.6.3/sysadmins/unix/server-ubuntu1804-ice36.html
that also sets it to 644. So that appears to be considered safe enough.

**Comment by dsudar** [comment]
Oh and when it's 640, for regular users psql --version gives:
`Error: Invalid data directory for cluster 11 main`
while for root it gives:
`psql (PostgreSQL) 11.12 (Ubuntu 11.12-1.pgdg20.04+1)`

**Comment by sbesson** [comment]
@dsudar `ome.postgresql` 5.0.3 has now been released with this fix. Thanks for reporting it
